# -*- coding: utf-8 -*-
"""PROJE 7 Fitness Takip Sistemi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1svHW1_Z94YNTFyTtuNdzgVOM1OnNjKOR
"""

import sqlite3
import os

def veritabanini_hazirla():
    """
    Bu fonksiyon, fitness takip sistemi için gerekli SQLite veritabanını hazırlar.
    Veritabanı bağlantısını kurar, tabloları (Sporcu, Antrenman, Takip) oluşturur,
    test verileri ekler, bir sporcunun ilerlemesini günceller ve gelişim raporunu yazdırır.
    """
    # Veritabanı bağlantısı oluşturulur.
    # Eğer 'fitness_takip.db' adında bir veritabanı dosyası yoksa, otomatik olarak oluşturulur.
    # Varsa, mevcut veritabanına bağlanılır.
    conn = sqlite3.connect('fitness_takip.db')
    # Veritabanı üzerinde SQL komutlarını çalıştırmak için bir cursor (imleç) nesnesi oluşturulur.
    cursor = conn.cursor()

    # 1. TABLOLARI OLUŞTURMA
    # Veritabanında gerekli tabloların varlığını kontrol eder ve yoksa oluşturur.
    # IF NOT EXISTS ifadesi, tablonun zaten var olması durumunda hata vermesini engeller.

    # Sporcu Tablosu
    # Sporcuların temel bilgilerini (ad, soyad, cinsiyet, boy, kilo, yağ oranı, kayıt tarihi) saklar.
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Sporcu (
        sporcu_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Her sporcu için benzersiz kimlik, otomatik artan.
        ad TEXT NOT NULL,                             -- Sporcunun adı, boş bırakılamaz.
        soyad TEXT NOT NULL,                          -- Sporcunun soyadı, boş bırakılamaz.
        cinsiyet TEXT CHECK (cinsiyet IN ('Erkek', 'Kadın')), -- Cinsiyet, sadece 'Erkek' veya 'Kadın' olabilir.
        boy REAL,                                     -- Sporcunun boyu (metre cinsinden olabilir).
        ilk_kilo REAL NOT NULL,                       -- Sporcunun sisteme ilk kayıt olduğu zamanki kilosu, boş bırakılamaz.
        guncel_kilo REAL NOT NULL,                    -- Sporcunun güncel kilosu, boş bırakılamaz.
        guncel_yag_orani REAL,                        -- Sporcunun güncel yağ oranı.
        kayit_tarihi DATETIME DEFAULT CURRENT_TIMESTAMP -- Sporcunun kayıt tarihi ve saati, varsayılan olarak mevcut zaman.
    )
    ''')

    # Antrenman Tablosu
    # Yapılan antrenmanların türünü ve süresini saklar.
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Antrenman (
        antrenman_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Her antrenman için benzersiz kimlik, otomatik artan.
        tur TEXT,                                     -- Antrenmanın türü (örn: 'Kuvvet Antrenmanı', 'Kardiyo').
        sure INTEGER                                  -- Antrenmanın süresi (dakika cinsinden).
    )
    ''')

    # Takip Tablosu
    # Sporcuların belirli bir tarihte yaptığı antrenmanları ve yakılan kaloriyi takip eder.
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Takip (
        takip_id INTEGER PRIMARY KEY AUTOINCREMENT,
        sporcu_id INTEGER,
        antrenman_id INTEGER,
        tarih DATE DEFAULT CURRENT_DATE,
        kalori_yakilan INTEGER,
        FOREIGN KEY (sporcu_id) REFERENCES Sporcu(sporcu_id),     -- Sporcu tablosundaki sporcu_id ile ilişkilidir.
        FOREIGN KEY (antrenman_id) REFERENCES Antrenman(antrenman_id) -- Antrenman tablosundaki antrenman_id ile ilişkilidir.
    )
    ''')

    # 2. VERİ EKLEME (Test Verileri)
    # Sistemin çalışmasını test etmek amacıyla başlangıç verileri eklenir.

    # Yeni Sporcu Ekle
    # 'Hakan Yılmaz' adında bir sporcu sisteme eklenir.
    cursor.execute('''
    INSERT INTO Sporcu (ad, soyad, cinsiyet, boy, ilk_kilo, guncel_kilo, guncel_yag_orani)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', ('Hakan', 'Yılmaz', 'Erkek', 1.82, 115.0, 115.0, 28.5))

    # Antrenman Ekle
    # 'Kuvvet Antrenmanı' adında 60 dakikalık bir antrenman türü eklenir.
    cursor.execute('INSERT INTO Antrenman (tur, sure) VALUES (?, ?)', ('Kuvvet Antrenmanı', 60))

    # Takip Kaydı Ekle
    # Hakan Yılmaz'ın (sporcu_id=1) yaptığı Kuvvet Antrenmanı'nı (antrenman_id=1) takip kaydı olarak ekler.
    # Bu antrenmanda 650 kalori yakıldığı varsayılır.
    cursor.execute('INSERT INTO Takip (sporcu_id, antrenman_id, kalori_yakilan) VALUES (?, ?, ?)', (1, 1, 650))

    # 3. İLERLEME KAYDET (Python Fonksiyonu Olarak)
    # Bir sporcunun kilo ve yağ oranı bilgilerini güncelleyen yardımcı bir fonksiyon.
    def ilerleme_kaydet(s_id, yeni_kilo, yeni_yag):
        """
        Belirtilen sporcu ID'sine sahip sporcunun güncel kilo ve yağ oranını günceller.
        :param s_id: Güncellenecek sporcunun ID'si.
        :param yeni_kilo: Sporcunun yeni güncel kilosu.
        :param yeni_yag: Sporcunun yeni güncel yağ oranı.
        """
        cursor.execute('''
        UPDATE Sporcu
        SET guncel_kilo = ?, guncel_yag_orani = ?
        WHERE sporcu_id = ?
        ''', (yeni_kilo, yeni_yag, s_id))

    # Hakan'ın (sporcu_id=1) gelişimini kaydet: Kilosunu 108.0 kg'a, yağ oranını 24.2'ye günceller.
    ilerleme_kaydet(1, 108.0, 24.2)

    # Veritabanında yapılan tüm değişiklikleri kalıcı hale getirir.
    conn.commit()

    # 4. GELİŞİM RAPORUNU SORGULA (View Mantığı)
    # Sporcuların başlangıç ve güncel kiloları arasındaki farkı, ayrıca yağ yüzdesini gösteren bir rapor oluşturur.
    # Bu, bir VIEW olmasa da, VIEW mantığına benzer şekilde belirli bir sorgu sonucunu sunar.
    print("--- SPORCU GELİŞİM RAPORU ---")
    cursor.execute('''
    SELECT
        ad || ' ' || soyad AS AdSoyad,
        ilk_kilo AS Baslangic,
        guncel_kilo AS Guncel,
        (ilk_kilo - guncel_kilo) AS Fark,
        guncel_yag_orani AS Yag_Yuzdesi
    FROM Sporcu
    ''')

    # Sorgu sonuçlarını satır satır döngüye alarak ekrana yazdırır.
    for row in cursor.fetchall():
        print(f"Sporcu: {row[0]} | Başlangıç: {row[1]}kg | Güncel: {row[2]}kg | Verilen: {row[3]}kg | Yağ: %{row[4]}")

    # Veritabanı bağlantısını kapatır. Kaynakların serbest bırakılması için önemlidir.
    conn.close()

if __name__ == "__main__":
    veritabanini_hazirla()